Revert "Revert "Merge pull request #45 from cybozu-go/go-1.16""
cybozu-go/neco-gcp pull request #75
Opened 2021-09-29 02:47 UTC by yamatcha

This reverts commit 298334eee406799de4c902076f2e5ba2cd3ff6ba.

2021-09-29 02:49 UTC, ymmt2005 commented
@yamatcha 
Also, update this line for Go 1.16:
```
necogcp-app/app.yaml:runtime: go113
```

2021-09-30 08:35 UTC, yokaze submitted a review, later dismissed
LGTM

2021-10-01 02:10 UTC, masa213f requested changes

2021-10-01 02:10 UTC, masa213f commented on .github/workflows/main.yaml
> +        go-version: ["1.16", "1.17"]
Could you remain this comment?  
Without this comment, we don't know why testing with go 1.16.

```suggestion
      # Cloud Functions does not support the latest Go runtimes. Currently, it only supports up to Go 1.16.
      # Therefore, this test confirms that the source is able to build with the supported Go version.
      matrix:
        go-version: ["1.16", "1.17"]
```

2021-10-04 02:02 UTC, masa213f approved these changes
LGTM

2021-10-04 02:02 UTC, merged